Alias /phpmyadmin /usr/share/phpmyadmin

<Directory /usr/share/phpmyadmin>
    Options SymLinksIfOwnerMatch
    DirectoryIndex index.php
    Require all granted
</Directory>

# Empêche l'accès direct au dossier interne
<Directory /usr/share/phpmyadmin/setup>
    Require all denied
</Directory>